### ISSUE TITLE
Why are all the actions removing the source and then re-downloading it?

### ISSUE THREAD

**Issue by bmorrissirromb** [aws-samples/aws-iam-identity-center-pipeline#2]
https://github.com/aws-samples/aws-iam-identity-center-pipeline/blob/f3d0b43641ba8b5cdb161652d48106af99093c5c/iam-identitycenter-pipeline.yaml#L243

**Comment by andrecvnt** [comment]
Good catch, remove this unnecessary step. Thanks for contributing.
