### ISSUE TITLE
Add check to ensure customer-managed policy exists prior to adding to permission set

### ISSUE THREAD

**Issue by bmorrissirromb** [aws-samples/aws-iam-identity-center-pipeline#5]
https://github.com/aws-samples/aws-iam-identity-center-pipeline/blob/1a869792e27b3c3393b177d2d447a03813e48a33/source/permissionsets/iam-identitycenter-permissionset.py#L214C35-L214C93

I need to reproduce this definitively, but my test-lab deployment of the solution was giving me this error during the Terraform Assignment:
```bash
Error: error waiting for SSO Permission Set (arn:aws:sso:::permissionSet/*) to provision: unexpected state 'FAILED', wanted target 'SUCCEEDED'. last error: %!s(<nil>)
```

The root cause was that I was trying to attach a customer-managed policy that did not actually exist. Once that was removed, the solution worked.

Terraform's error messages when this happens are not very useful, so I would consider adding a check here (even a simple try-catch based on the `get_policy` boto3 command) to prevent downstream issues.

**Comment by andrecvnt** [comment]
The thing with **customer-managed-policy** is that it needs to exist in every AWS account you are assigning the permission set, so its validation will be costly and won't scale. 

That’s why there is a **IMPORTANT** disclaimer at the [Best Practice](https://github.com/aws-samples/aws-iam-identity-center-pipeline#best-practices) section in the README.md file.

I am will try to treat this error to return something friendly to users in the pipeline.
